management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  metrics:
    export:
      influx:
        auto-create-db: true
        compressed: true
        db: my-influx-db
        enabled: true
        step: 15s
        uri: http://localhost:8086